from uuid import uuid4 as uuid
import logging as log
import requests
import time
import sys
import os

log.basicConfig(level=log.DEBUG, stream=sys.stdout)

import helpful_test_functions as helpers

urls = [url for url in helpers.generate_test_urls(10)]
imgs = [img for img in helpers.generate_test_images(10)]
r = helpers.requests_log_wrapper(requests)

for test_url, img in zip(urls, imgs):
    try:
        response = r.get(test_url)
        assert (
            500 >= response.status_code >= 400
        ), f"""
        Failed to check that running against an unknown test id would
        result in a 4xx response.

        url={test_url}

        {response.text}

        """
        body = {
            "domain": uuid().hex,
            "build_id": uuid().hex,
            "run_id": uuid().hex,
            "image": img,
            "model_type": "default",
        }
        response = r.post(test_url, json=body)
        assert (
            200 == response.status_code
        ), f"""
        Failed to create a request 

        url={test_url}
        body={body}

        {response.text}
        """
        time.sleep(5)

        response = r.get(test_url)
        assert (
            200 == response.status_code
        ), f"""
        Failed to retrieve previously created configuration 

        url={test_url}

        {response.text}
        """
        data = response.json()
        assert all(
            [
                data[0]["build_id"] == body["build_id"],
                data[0]["run_id"] == body["run_id"],
            ]
        ), f"""
        Expected build_id and run_id to match exactly

        url={test_url}
        build_id={body['build_id']}
        run_id={body['run_id']}

        {data}
        """
    finally:
        response = r.delete(test_url + "?clear_all_records=true")
        assert (
            200 == response.status_code
        ), f"""
        Failed to delete test record. Watch out we still have lingering shit!

        url={test_url}

        {response.text}
        """
